GET http://localhost:8080/api/properties
Content-Type: application/json

###

GET http://localhost:8080/api/properties/646f7dc0194b508e1b50f4b3
Content-Type: application/json

###

POST http://localhost:8080/api/properties
Content-Type: application/json

[
    {
        "city": "Manchester",
        "country": "England",
        "lat": 53.474096,
        "lon": -2.251063,
        "description": "An apartment looking over Manchester",
        "caption": "A great apartment looking over Deansgate",
        "rating": 4.5,
        "perNightPrice": 90.00,
        "totalPrice": 800.00,
        "heroImg": "https://source.unsplash.com/YAPZt8wxMO4",
        "images": [
            "https://source.unsplash.com/ONKp84V3ZVs",
            "https://source.unsplash.com/Aac7IlKnYX8",
            "https://source.unsplash.com/GQQyH0yNqLk"
        ],
        "dateFrom": "2023/09/01",
        "dateTo": "2023/09/07",
        "numRooms": 2,
        "numBeds": 2,
        "numToilets": 2,
        "numVotes": 300,
        "sharedProperty": false,
        "region": "Europe"
    },
    {
        "city": "Milan",
        "country": "Italy",
        "lat": 45.464194,
        "lon": 9.189635,
        "description": "Double room in lovely apartment",
        "caption": "Stay with Valentina",
        "rating": 4.4,
        "perNightPrice": 50.00,
        "totalPrice": 400.00,
        "heroImg": "https://source.unsplash.com/Wp7t4cWN-68",
        "images": [
            "https://source.unsplash.com/Yrxr3bsPdS0",
            "https://source.unsplash.com/6TY_WrJTwSI",
            "https://source.unsplash.com/kjh70RMHDco"
        ],
        "dateFrom": "2023/08/01",
        "dateTo": "2023/08/07",
        "numRooms": 2,
        "numBeds": 2,
        "numToilets": 2,
        "numVotes": 100,
        "sharedProperty": false,
        "region": "Europe"
    },
    {
        "city": "Ottawa",
        "country": "Canada",
        "lat": 45.420878,
        "lon": -75.690111,
        "description": "Stay in the wild in this cabin",
        "caption": "A break away from the city",
        "rating": 4.8,
        "perNightPrice": 30.00,
        "totalPrice": 271.00,
        "heroImg": "https://source.unsplash.com/paydk0JcIOQ",
        "images": [
            "https://source.unsplash.com/nEtpvJjnPVo",
            "https://source.unsplash.com/P_0tnQ8hb70",
            "vp4yWCNA2_6Q"
        ],
        "dateFrom": "2023/10/01",
        "dateTo": "2023/10/07",
        "numRooms": 1,
        "numBeds": 1,
        "numToilets": 1,
        "numVotes": 100,
        "sharedProperty": false,
        "region": "United States"
    },
    {
        "city": "London",
        "country": "UK",
        "lat": 51.507336,
        "lon": -0.127650,
        "description": "Stunning one bed apartment",
        "caption": "Be close to the city with loads of things to do",
        "rating": 4.3,
        "perNightPrice": 70.00,
        "totalPrice": 330.00,
        "heroImg": "https://source.unsplash.com/_HqHX3LBN18",
        "images": [
            "https://source.unsplash.com/GqbU78bdJFM",
            "https://source.unsplash.com/FJLoqqIsSHc",
            "https://source.unsplash.com/TZ_Aj8a5SW8"
        ],
        "dateFrom": "2023/11/01",
        "dateTo": "2023/11/07",
        "numRooms": 1,
        "numBeds": 1,
        "numToilets": 1,
        "numVotes": 400,
        "sharedProperty": false,
        "region": "Europe"
    },
    {
        "city": "Los Angeles, California",
        "country": "USA",
        "lat": 34.053691,
        "lon": -118.242766,
        "description": "Two bedroom house in LA",
        "caption": "Live with the stars",
        "rating": 4.2,
        "perNightPrice": 120.00,
        "totalPrice": 571.00,
        "heroImg": "https://source.unsplash.com/YAPZt8wxMO4",
        "images": [
            "https://source.unsplash.com/vOa-PSimwg4",
            "https://source.unsplash.com/g51F6-WYzyU",
            "https://source.unsplash.com/OPTtVaI8H2Q"
        ],
        "dateFrom": "2023/11/01",
        "dateTo": "2023/11/07",
        "numRooms": 2,
        "numBeds": 2,
        "numToilets": 2,
        "numVotes": 500,
        "sharedProperty": true,
        "region": "United States"
    },
    {
        "city": "Paris",
        "country": "France",
        "lat": 48.853495,
        "lon": 2.348391,
        "description": "A lovely apartment in the love capital",
        "caption": "Have a romantic break in my little hideaway",
        "rating": 4.4,
        "perNightPrice": 110.00,
        "totalPrice": 471.00,
        "heroImg": "https://source.unsplash.com/kyt0PkBSCNQ",
        "images": [
            "https://source.unsplash.com/hCU4fimRW-c",
            "https://source.unsplash.com/1AF5hP6F4tI",
            "https://source.unsplash.com/yoSb_GcodHo"
        ],
        "dateFrom": "2023/12/10",
        "dateTo": "2023/12/14",
        "numRooms": 1,
        "numBeds": 1,
        "numToilets": 1,
        "numVotes": 300,
        "sharedProperty": false,
        "region": "France"
    },
    {
        "city": "Mexixo City",
        "country": "Mexico",
        "lat": 19.432630,
        "lon": -99.133178,
        "description": "Room in apartment, traditional neighbourhood",
        "caption": "Sit back and relax with tacos",
        "rating": 4.2,
        "perNightPrice": 55.00,
        "totalPrice": 290.00,
        "heroImg": "https://source.unsplash.com/0sDzRgrN_pI",
        "images": [
            "https://source.unsplash.com/qd5yc3hpaco",
            "https://source.unsplash.com/R-FwAN1qz74",
            "https://source.unsplash.com/SByfd_e-s2c"
        ],
        "dateFrom": "2024/04/01",
        "dateTo": "2024/04/07",
        "numRooms": 1,
        "numBeds": 1,
        "numToilets": 1,
        "numVotes": 100,
        "sharedProperty": false,
        "region": "United States"
    },
    {
        "city": "Edinburgh",
        "country": "Scotland",
        "lat": 55.953346,
        "lon": -3.188375,
        "description": "A nice get away surrounded by culture",
        "caption": "Capture some of Scotland's finest heritage",
        "rating": 3.8,
        "perNightPrice": 115.00,
        "totalPrice": 471.00,
        "heroImg": "https://source.unsplash.com/rEJxpBskj3Q",
        "images": [
            "https://source.unsplash.com/qGNgjHQjO2k",
            "https://source.unsplash.com/fh-iC1o2QOM",
            "https://source.unsplash.com/-PIntD0VM1o"
        ],
        "dateFrom": "2023/12/01",
        "dateTo": "2023/12/07",
        "numRooms": 1,
        "numBeds": 1,
        "numToilets": 1,
        "numVotes": 150,
        "sharedProperty": false,
        "region": "Europe"
    },
    {
        "city": "Copacabana",
        "country": "Brazil",
        "lat": -22.971974,
        "lon": -43.184300,
        "description": "Two bed apartment close to the beach",
        "caption": "A bit of samba? Why not",
        "rating": 5.0,
        "perNightPrice": 45.00,
        "totalPrice": 371.00,
        "heroImg": "https://source.unsplash.com/L7EwHkq1B2s",
        "images": [
            "https://source.unsplash.com/4HUhp0vwkbM",
            "https://source.unsplash.com/rT0zaQn2r5o",
            "https://source.unsplash.com/Qsgxa7L8YfY"
        ],
        "dateFrom": "2024/02/01",
        "dateTo": "2024/02/07",
        "numRooms": 2,
        "numBeds": 2,
        "numToilets": 2,
        "numVotes": 500,
        "sharedProperty": false,
        "region": "South America"
    }
]